[package]
name = "create_chat_completion_default"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
pplx_client = { path = "./../../../pplx-client" }
tokio = { version = "1.0", features = ["full"] }
